### ISSUE TITLE
Could not resolve dependency peer react-native@"0.57.4"

### ISSUE THREAD

**Issue by christophemarois** [communitybuilders/react-native-test-flight#1]
Hi!

With this specified in your `package.json`

```json
{
  "peerDependencies": {
    "react-native": "0.57.4"
  }
}
```

The most recent npm will [prevent installation](https://stackoverflow.com/a/66620869/1558527) even in my case, running `react-native@0.63.3`. A simple solution would be to change the semver to `>0.57.4` (for *any version greater than*), or just removing the statement entirely.

Quick fix for anyone who finds this: Add a `.npmrc` to your project's root and add this line to it: `legacy-peer-deps=true`

**Comment by dejan9393** [comment]
Hi. Thanks for the report! I'm running on an older version of npm so I wasn't hitting this - I've fixed that up and published the patch in v1.0.4
